version: "3.9"


services:
  ohmyurl-postgres:
    container_name: "ohmyurl-postgresql"
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./config/postgresql/.env
    volumes:
      - ohmyurl_postgresqo_data:/var/lib/postgresql/data
    init: true

  ohmyurl-web:
    container_name: "ohmyurl-web"
    build: .
    image: ohmyurl-web:1.1
    env_file:
      - ./app/config/.env
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ohmyurl-postgres
    init: true

  ohmyurl-nginx:
    container_name: "ohmyurl-nginx"
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ohmyurl-web
    init: true

volumes:
  ohmyurl_postgresqo_data:
